import React from "react";
const columns = [
  {name: "NAME", uid: "businessName", sortable: true},
  {name: "REGISTRATION NUMBER", uid: "id", sortable: true},
  {name:"MAIN CONTACT", uid: "mainNumber"},
  {name: "ALTERNATIVE CONTACT", uid: "altNumber", sortable: true},
  {name: "ADDRESS 1", uid: "addressLine1", sortable: true},
  {name: "ADDRESS 2", uid: "addressLine2", sortable: true},
  {name: "POSTAL CODE", uid: "postalCode", sortable: true},
  {name: "CITY" , uid: "city", sortable: true},
  {name: "PROVINCE", uid: "province"},
  {name: "STATUS", uid: "verifyStatus"},
  {name: "ACTIONS", uid: "actions"},
];

const statusOptions = [
  {name: "verified", uid: "verified"},
  {name: "rejected", uid: "rejected"},
];

// const consigners = [
//   {
//     businessName: "Advantis",
//     id: "bn123",
//     main: "0775006920",
//     alter: "0779996325",
//     add1: "283/D/F",
//     add2: "Periyamulla Negombo",
//     postal: "11500",
//     city: "Negombo",
//     province: "Gampaha",
//     status: 'Verified',
//   },
//   {
//     name: "Hukaris",
//     id: "bn12",
//     main: "0775006920",
//     alter: "0779996325",
//     add1: "283/D/F",
//     add2: "Periyamulla Negombo",
//     postal: "11500",
//     city: "Negombo",
//     province: "Gampaha",
//     status: 'Not Verified',
//   },
//   {
//     name: "Advantis",
//     id: "bn24",
//     main: "0775006920",
//     alter: "0779996325",
//     add1: "283/D/F",
//     add2: "Periyamulla Negombo",
//     postal: "11500",
//     city: "Negombo",
//     province: "Gampaha",
//     status: 'Not Verified',
//   },
//   {
//     name: "Advantis",
//     id: "bn65",
//     main: "0775006920",
//     alter: "0779996325",
//     add1: "283/D/F",
//     add2: "Periyamulla Negombo",
//     postal: "11500",
//     city: "Negombo",
//     province: "Gampaha",
//     status: 'Not Verified',
//   },
//   {
//     name: "Advantis",
//     id: "bn79",
//     main: "0775006920",
//     alter: "0779996325",
//     add1: "283/D/F",
//     add2: "Periyamulla Negombo",
//     postal: "11500",
//     city: "Negombo",
//     province: "Gampaha",
//     status: 'Verified',
//   },
//   {
//     name: "Advantis",
//     id: "bn75",
//     main: "0775006920",
//     alter: "0779996325",
//     add1: "283/D/F",
//     add2: "Periyamulla Negombo",
//     postal: "11500",
//     city: "Negombo",
//     province: "Gampaha",
//     status: 'Verified',
//   },
  
// ];

export {columns,  statusOptions};