import React from "react";
const columns = [
  {name: "ID", uid: "id", sortable: true},
  {name: "VEHICLE", uid: "vehicle", sortable: true},
  {name:"IMAGE", uid: "image"},
  {name: "STARTING ROUTE", uid: "sroute", sortable: true},
  {name: "ENDINGrOUTE", uid: "eroute", sortable: true},
  {name: "STATUS", uid: "status", sortable: true},
  {name: "PROGRESS", uid: "progress", sortable: true},
  {name: "DRIVER" , uid: "driver", sortable: true},
  {name: "ACTIONS", uid: "actions"},
];

const statusOptions = [
  {name: "Oil Leakage", uid: "Oil Leakage"},
  {name: "No Warnings", uid: "No Warnings"},
  {name: "Stopped", uid: "Stopped"},
  {name: "Consignee not available", uid: "Consignee not available"},
  {name: "Fuel Problem", uid: "Fuel Problem"},

];

const vehicles = [
  {
    id: 1,
    vehicle: "KAW 123",
    type: "Truck",
    image: "https://via.placeholder.com/150",
    sroute: "Pettah",
    sdate: "2024-01-23",
    eroute: "Kandy",
    edate: "2024-01-23",
    status: "Oil Leakage",
    progress: 50,
    driver: "Amal Perera",
  },
  {
    id: 2,
    vehicle: "KAW 124",
    type: "Truck",
    image: "https://via.placeholder.com/150",
    sroute: "Pettah",
    sdate: "2024-01-23",
    eroute: "Kandy",
    edate: "2024-01-23",
    status: "No Warnings",
    progress: 60,
    driver: "Sunil Perera",
  },
  {
    id: 3,
    vehicle: "KAW 125",
    type: "Truck",
    image: "https://via.placeholder.com/150",
    sroute: "Pettah",
    sdate: "2024-01-23",
    eroute: "Kandy",
    edate: "2024-01-23",
    status: "Stopped",
    progress: 70,
    driver: "Kamal Perera",
  },
  {
    id: 4,
    vehicle: "KAW 126",
    type: "Truck",
    image: "https://via.placeholder.com/150",
    sroute: "Pettah",
    sdate: "2024-01-23",
    eroute: "Kandy",
    edate: "2024-01-23",
    status: "Consignee not available",
    progress: 80,
    driver: "Nimal Perera",
  },
  {
    id: 5,
    vehicle: "KAW 127",
    type: "Truck",
    image: "https://via.placeholder.com/150",
    sroute: "Pettah",
    sdate: "2024-01-23",
    eroute: "Kandy",
    edate: "2024-01-23",
    status: "Fuel Problem",
    progress: 90,
    driver: "Sunil Perera",
  }
  ,
  {
    id:6,
    vehicle: "KAW 128",
    type: "Truck",
    image: "https://via.placeholder.com/150",
    sroute: "Pettah",
    sdate: "2024-01-23",
    eroute: "Kandy",
    edate: "2024-01-23",
    status: "No warnings",
    progress: 90,
    driver: "Sunil Perera",
  },
  {
    id: 7,
    vehicle: "KAW 129",
    type: "Truck",
    image: "https://via.placeholder.com/150",
    sroute: "Pettah",
    sdate: "2024-01-23",
    eroute: "Kandy",
    edate: "2024-01-23",
    status: "No Warnings",
    progress: 80,
    driver: "Kamal Perera",
  },
  {
    id: 8,
    vehicle: "KAW 130",
    type: "Truck",
    image: "https://via.placeholder.com/150",
    sroute: "Pettah",
    sdate: "2024-01-23",
    eroute: "Kandy",
    edate: "2024-01-23",
    status: "Stopped",
    progress: 70,
    driver: "Nimal Perera",
  },
  {
    id: 9,
    vehicle: "KAW 131",
    type: "Truck",
    image: "https://via.placeholder.com/150",
    sroute: "Pettah",
    sdate: "2024-01-23",
    eroute: "Kandy",
    edate: "2024-01-23",
    status: "Consignee not available",
    progress: 60,
    driver: "Amal Perera",
  },
  
];

export {columns, vehicles, statusOptions};