// VehicleDrivers.ts
export const driverColumns = [
    { name: "Driver ID", uid: "id", sortable: true },
    { name: "Full Name", uid: "fullName", sortable: true },
    { name: "Date of Birth", uid: "dob", sortable: true },
    { name: "Contact Details", uid: "contactDetails" },
    { name: "Address", uid: "address" },
    { name: "License Number", uid: "licenseNumber", sortable: true },
    { name: "License Type", uid: "licenseType", sortable: true },
    { name: "License Expiry", uid: "licenseExpiry", sortable: true },
    { name: "Certifications", uid: "certifications" },
    { name: "Employment Status", uid: "employmentStatus", sortable: true },
    { name: "Hire Date", uid: "hireDate", sortable: true },
    { name: "Experience", uid: "experience", sortable: true },
    { name: "Training Records", uid: "trainingRecords" },
    { name: "Performance Reviews", uid: "performanceReviews" },
    { name: "Current Vehicle ID", uid: "currentVehicleId", sortable: true },
    { name: "Previous Vehicles Driven", uid: "previousVehicles" },
    { name: "Preferred Vehicle Type", uid: "preferredVehicleType", sortable: true },
    { name: "Medical Certifications", uid: "medicalCertifications" },
    { name: "Drug/Alcohol Tests", uid: "drugTests" },
    { name: "Accident History", uid: "accidentHistory" },
    { name: "Safety Training", uid: "safetyTraining" },
    { name: "Work Hours", uid: "workHours", sortable: true },
    { name: "Shift Patterns", uid: "shiftPatterns" },
    { name: "Availability", uid: "availability", sortable: true },
  ];
  
  export const licenseTypes = [
    { name: "CDL", uid: "cdl" },
    { name: "HGV", uid: "hgv" },
    { name: "LGV", uid: "lgv" },
  ];
  
  export const employmentStatuses = [
    { name: "Full-Time", uid: "full_time" },
    { name: "Part-Time", uid: "part_time" },
    { name: "Contract", uid: "contract" },
  ];
  
  export const preferredVehicleTypes = [
    { name: "HGV", uid: "hgv" },
    { name: "LCV", uid: "lcv" },
    { name: "SV", uid: "sv" },
  ];
  
  export const drivers = [
    {
      id: 1,
      fullName: "Amal Perera",
      dob: "1980-01-01",
      contactDetails: { phone: "123-456-7890", email: "amal.perera@drivers.com" },
      address: "123 Driver St, City, Country",
      licenseNumber: "LIC12345",
      licenseType: "CDL",
      licenseExpiry: "2025-01-01",
      certifications: ["Hazmat"],
      employmentStatus: "Full-Time",
      hireDate: "2015-06-15",
      experience: "15 years",
      trainingRecords: ["Safety Training 2021"],
      performanceReviews: ["Excellent"],
      currentVehicleId: 1,
      previousVehicles: ["Volvo FH Series"],
      preferredVehicleType: "HGV",
      medicalCertifications: ["Medical Cert 2023"],
      drugTests: "Negative",
      accidentHistory: "None",
      safetyTraining: ["Safety Training 2021"],
      workHours: "40 hours/week",
      shiftPatterns: ["Day Shift"],
      availability: "Available",
    },
    {
      id: 2,
      fullName: "Sunil Perera",
      dob: "1985-03-15",
      contactDetails: { phone: "234-567-8901", email: "sunil.perera@drivers.com" },
      address: "456 Transport Ave, City, Country",
      licenseNumber: "LIC54321",
      licenseType: "HGV",
      licenseExpiry: "2024-06-30",
      certifications: ["Forklift"],
      employmentStatus: "Part-Time",
      hireDate: "2018-02-20",
      experience: "10 years",
      trainingRecords: ["Forklift Training 2022"],
      performanceReviews: ["Good"],
      currentVehicleId: 2,
      previousVehicles: ["Scania R Series"],
      preferredVehicleType: "LCV",
      medicalCertifications: ["Medical Cert 2022"],
      drugTests: "Negative",
      accidentHistory: "Minor Incident 2021",
      safetyTraining: ["Safety Training 2022"],
      workHours: "20 hours/week",
      shiftPatterns: ["Night Shift"],
      availability: "Available",
    },
    {
      id: 3,
      fullName: "Kamal Perera",
      dob: "1990-07-21",
      contactDetails: { phone: "345-678-9012", email: "kamal.perera@drivers.com" },
      address: "789 Fleet Rd, City, Country",
      licenseNumber: "LIC67890",
      licenseType: "LGV",
      licenseExpiry: "2025-12-31",
      certifications: ["Hazmat", "Forklift"],
      employmentStatus: "Contract",
      hireDate: "2020-08-10",
      experience: "5 years",
      trainingRecords: ["Safety Training 2020"],
      performanceReviews: ["Satisfactory"],
      currentVehicleId: 3,
      previousVehicles: ["Mercedes-Benz Actros"],
      preferredVehicleType: "HGV",
      medicalCertifications: ["Medical Cert 2021"],
      drugTests: "Negative",
      accidentHistory: "None",
      safetyTraining: ["Safety Training 2020"],
      workHours: "30 hours/week",
      shiftPatterns: ["Day Shift"],
      availability: "Not Available",
    },
    {
      id: 4,
      fullName: "Nimal Perera",
      dob: "1982-11-11",
      contactDetails: { phone: "456-789-0123", email: "nimal.perera@drivers.com" },
      address: "321 Haulage Ln, City, Country",
      licenseNumber: "LIC90123",
      licenseType: "CDL",
      licenseExpiry: "2024-03-31",
      certifications: ["Hazmat", "Forklift"],
      employmentStatus: "Full-Time",
      hireDate: "2012-09-05",
      experience: "12 years",
      trainingRecords: ["Safety Training 2019"],
      performanceReviews: ["Excellent"],
      currentVehicleId: 4,
      previousVehicles: ["Renault T-Series"],
      preferredVehicleType: "HGV",
      medicalCertifications: ["Medical Cert 2020"],
      drugTests: "Negative",
      accidentHistory: "None",
      safetyTraining: ["Safety Training 2019"],
      workHours: "40 hours/week",
      shiftPatterns: ["Day Shift"],
      availability: "Available",
    },
    {
      id: 5,
      fullName: "Ajith Silva",
      dob: "1978-05-09",
      contactDetails: { phone: "567-890-1234", email: "ajith.silva@drivers.com" },
      address: "987 Urban Blvd, City, Country",
      licenseNumber: "LIC23456",
      licenseType: "HGV",
      licenseExpiry: "2024-11-30",
      certifications: ["Forklift"],
      employmentStatus: "Part-Time",
      hireDate: "2017-03-12",
      experience: "18 years",
      trainingRecords: ["Forklift Training 2018"],
      performanceReviews: ["Good"],
      currentVehicleId: 5,
      previousVehicles: ["DAF XF"],
      preferredVehicleType: "LCV",
      medicalCertifications: ["Medical Cert 2022"],
      drugTests: "Negative",
      accidentHistory: "Minor Incident 2020",
      safetyTraining: ["Safety Training 2021"],
      workHours: "25 hours/week",
      shiftPatterns: ["Night Shift"],
      availability: "Available",
    },
    {
      id: 6,
      fullName: "Chathura Jayasinghe",
      dob: "1983-12-12",
      contactDetails: { phone: "678-901-2345", email: "chathura.jayasinghe@drivers.com" },
      address: "654 Cargo Pl, City, Country",
      licenseNumber: "LIC34567",
      licenseType: "LGV",
      licenseExpiry: "2025-07-31",
      certifications: ["Hazmat"],
      employmentStatus: "Contract",
      hireDate: "2019-11-01",
      experience: "7 years",
      trainingRecords: ["Safety Training 2021"],
      performanceReviews: ["Satisfactory"],
      currentVehicleId: 6,
      previousVehicles: ["Volvo FM"],
      preferredVehicleType: "HGV",
      medicalCertifications: ["Medical Cert 2023"],
      drugTests: "Negative",
      accidentHistory: "None",
      safetyTraining: ["Safety Training 2021"],
      workHours: "35 hours/week",
      shiftPatterns: ["Day Shift"],
      availability: "Not Available",
    },
    {
      id: 7,
      fullName: "Nihal Fernando",
      dob: "1989-03-03",
      contactDetails: { phone: "789-012-3456", email: "nihal.fernando@drivers.com" },
      address: "321 Fleet St, City, Country",
      licenseNumber: "LIC45678",
      licenseType: "CDL",
      licenseExpiry: "2024-10-31",
      certifications: ["Forklift"],
      employmentStatus: "Full-Time",
      hireDate: "2016-05-20",
      experience: "8 years",
      trainingRecords: ["Forklift Training 2019"],
      performanceReviews: ["Good"],
      currentVehicleId: 7,
      previousVehicles: ["Iveco Stralis"],
      preferredVehicleType: "HGV",
      medicalCertifications: ["Medical Cert 2021"],
      drugTests: "Negative",
      accidentHistory: "Minor Incident 2019",
      safetyTraining: ["Safety Training 2020"],
      workHours: "40 hours/week",
      shiftPatterns: ["Night Shift"],
      availability: "Available",
    },
    {
      id: 8,
      fullName: "Mahesh Perera",
      dob: "1975-07-07",
      contactDetails: { phone: "890-123-4567", email: "mahesh.perera@drivers.com" },
      address: "123 Transport St, City, Country",
      licenseNumber: "LIC56789",
      licenseType: "HGV",
      licenseExpiry: "2024-04-30",
      certifications: ["Hazmat", "Forklift"],
      employmentStatus: "Part-Time",
      hireDate: "2013-08-14",
      experience: "20 years",
      trainingRecords: ["Safety Training 2020"],
      performanceReviews: ["Excellent"],
      currentVehicleId: 8,
      previousVehicles: ["Mercedes-Benz Vario"],
      preferredVehicleType: "LCV",
      medicalCertifications: ["Medical Cert 2021"],
      drugTests: "Negative",
      accidentHistory: "None",
      safetyTraining: ["Safety Training 2020"],
      workHours: "30 hours/week",
      shiftPatterns: ["Day Shift"],
      availability: "Not Available",
    },
    {
      id: 9,
      fullName: "Ruwan Liyanage",
      dob: "1984-09-09",
      contactDetails: { phone: "901-234-5678", email: "ruwan.liyanage@drivers.com" },
      address: "456 Logistics Ln, City, Country",
      licenseNumber: "LIC67890",
      licenseType: "LGV",
      licenseExpiry: "2025-08-31",
      certifications: ["Forklift"],
      employmentStatus: "Contract",
      hireDate: "2021-01-05",
      experience: "5 years",
      trainingRecords: ["Safety Training 2021"],
      performanceReviews: ["Satisfactory"],
      currentVehicleId: 9,
      previousVehicles: ["DAF CF"],
      preferredVehicleType: "HGV",
      medicalCertifications: ["Medical Cert 2023"],
      drugTests: "Negative",
      accidentHistory: "None",
      safetyTraining: ["Safety Training 2021"],
      workHours: "35 hours/week",
      shiftPatterns: ["Night Shift"],
      availability: "Available",
    },
    {
      id: 10,
      fullName: "Saman Gunawardena",
      dob: "1986-11-11",
      contactDetails: { phone: "012-345-6789", email: "saman.gunawardena@drivers.com" },
      address: "789 Cargo Rd, City, Country",
      licenseNumber: "LIC78901",
      licenseType: "CDL",
      licenseExpiry: "2024-05-31",
      certifications: ["Hazmat"],
      employmentStatus: "Full-Time",
      hireDate: "2014-04-18",
      experience: "10 years",
      trainingRecords: ["Safety Training 2022"],
      performanceReviews: ["Excellent"],
      currentVehicleId: 10,
      previousVehicles: ["Renault D-Series"],
      preferredVehicleType: "HGV",
      medicalCertifications: ["Medical Cert 2022"],
      drugTests: "Negative",
      accidentHistory: "None",
      safetyTraining: ["Safety Training 2022"],
      workHours: "40 hours/week",
      shiftPatterns: ["Day Shift"],
      availability: "Available",
    },
    {
      id: 11,
      fullName: "Pasan Jayasuriya",
      dob: "1981-02-14",
      contactDetails: { phone: "234-567-8901", email: "pasan.jayasuriya@drivers.com" },
      address: "987 Cargo Blvd, City, Country",
      licenseNumber: "LIC89012",
      licenseType: "HGV",
      licenseExpiry: "2025-09-30",
      certifications: ["Forklift"],
      employmentStatus: "Part-Time",
      hireDate: "2011-06-25",
      experience: "15 years",
      trainingRecords: ["Forklift Training 2017"],
      performanceReviews: ["Good"],
      currentVehicleId: 11,
      previousVehicles: ["Volvo FL"],
      preferredVehicleType: "LCV",
      medicalCertifications: ["Medical Cert 2021"],
      drugTests: "Negative",
      accidentHistory: "Minor Incident 2018",
      safetyTraining: ["Safety Training 2019"],
      workHours: "25 hours/week",
      shiftPatterns: ["Night Shift"],
      availability: "Available",
    },
    {
      id: 12,
      fullName: "Ruwan Liyanage",
      dob: "1987-05-19",
      contactDetails: { phone: "345-678-9012", email: "ruwan.liyanage@drivers.com" },
      address: "654 Transport Ave, City, Country",
      licenseNumber: "LIC90123",
      licenseType: "LGV",
      licenseExpiry: "2025-12-31",
      certifications: ["Hazmat", "Forklift"],
      employmentStatus: "Contract",
      hireDate: "2022-08-01",
      experience: "7 years",
      trainingRecords: ["Safety Training 2020"],
      performanceReviews: ["Satisfactory"],
      currentVehicleId: 12,
      previousVehicles: ["Mercedes-Benz Actros"],
      preferredVehicleType: "HGV",
      medicalCertifications: ["Medical Cert 2023"],
      drugTests: "Negative",
      accidentHistory: "None",
      safetyTraining: ["Safety Training 2020"],
      workHours: "35 hours/week",
      shiftPatterns: ["Day Shift"],
      availability: "Available",
    },
    {
      id: 13,
      fullName: "Nihal Fernando",
      dob: "1988-07-07",
      contactDetails: { phone: "456-789-0123", email: "nihal.fernando@drivers.com" },
      address: "321 Haulage Ln, City, Country",
      licenseNumber: "LIC01234",
      licenseType: "CDL",
      licenseExpiry: "2024-11-30",
      certifications: ["Forklift"],
      employmentStatus: "Full-Time",
      hireDate: "2015-11-05",
      experience: "9 years",
      trainingRecords: ["Forklift Training 2019"],
      performanceReviews: ["Good"],
      currentVehicleId: 13,
      previousVehicles: ["Volvo FH Series"],
      preferredVehicleType: "HGV",
      medicalCertifications: ["Medical Cert 2021"],
      drugTests: "Negative",
      accidentHistory: "Minor Incident 2019",
      safetyTraining: ["Safety Training 2020"],
      workHours: "40 hours/week",
      shiftPatterns: ["Night Shift"],
      availability: "Available",
    },
    {
      id: 14,
      fullName: "Nimal Perera",
      dob: "1983-04-04",
      contactDetails: { phone: "567-890-1234", email: "nimal.perera@drivers.com" },
      address: "987 Urban Blvd, City, Country",
      licenseNumber: "LIC12345",
      licenseType: "HGV",
      licenseExpiry: "2024-10-31",
      certifications: ["Hazmat", "Forklift"],
      employmentStatus: "Part-Time",
      hireDate: "2013-02-10",
      experience: "11 years",
      trainingRecords: ["Safety Training 2021"],
      performanceReviews: ["Good"],
      currentVehicleId: 14,
      previousVehicles: ["Scania R Series"],
      preferredVehicleType: "LCV",
      medicalCertifications: ["Medical Cert 2022"],
      drugTests: "Negative",
      accidentHistory: "Minor Incident 2020",
      safetyTraining: ["Safety Training 2021"],
      workHours: "30 hours/week",
      shiftPatterns: ["Day Shift"],
      availability: "Available",
    },
    {
      id: 15,
      fullName: "Ajith Silva",
      dob: "1985-12-15",
      contactDetails: { phone: "678-901-2345", email: "ajith.silva@drivers.com" },
      address: "654 Cargo Pl, City, Country",
      licenseNumber: "LIC23456",
      licenseType: "LGV",
      licenseExpiry: "2025-06-30",
      certifications: ["Hazmat"],
      employmentStatus: "Contract",
      hireDate: "2019-07-20",
      experience: "10 years",
      trainingRecords: ["Safety Training 2020"],
      performanceReviews: ["Satisfactory"],
      currentVehicleId: 15,
      previousVehicles: ["Renault T-Series"],
      preferredVehicleType: "HGV",
      medicalCertifications: ["Medical Cert 2021"],
      drugTests: "Negative",
      accidentHistory: "None",
      safetyTraining: ["Safety Training 2020"],
      workHours: "35 hours/week",
      shiftPatterns: ["Day Shift"],
      availability: "Available",
    },
  ];
  