export const supplierColumns = [
    { name: "Supplier ID", uid: "id", sortable: true },
    { name: "Company Name", uid: "companyName", sortable: true },
    { name: "Contact Person Name", uid: "contactPerson", sortable: true },
    { name: "Contact Details", uid: "contactDetails" },
    { name: "Address", uid: "address" },
    { name: "Registration Number", uid: "registrationNumber", sortable: true },
    { name: "Tax ID", uid: "taxId", sortable: true },
    { name: "Years in Operation", uid: "yearsInOperation", sortable: true },
    { name: "Type of Supplier", uid: "supplierType", sortable: true },
    { name: "Industry Certifications", uid: "industryCertifications" },
    { name: "Vehicles Info", uid: "vehiclesInfo" },
    { name: "Payment Terms", uid: "paymentTerms" },
    { name: "Bank Details", uid: "bankDetails" },
    { name: "Credit Rating", uid: "creditRating", sortable: true },
    { name: "Pricing List", uid: "pricingList" },
    { name: "Contract Details", uid: "contractDetails" },
    { name: "Compliance", uid: "compliance" },
    { name: "Legal Disputes", uid: "legalDisputes" },
  ];
  
  export const supplierTypes = [
    { name: "Manufacturer", uid: "manufacturer" },
    { name: "Leasing Company", uid: "leasing_company" },
    { name: "Distributor", uid: "distributor" },
    { name: "Retailer", uid: "retailer" },
  ];
  
  export const industryCertifications = [
    { name: "ISO 9001", uid: "iso_9001" },
    { name: "ISO 14001", uid: "iso_14001" },
    { name: "ISO 45001", uid: "iso_45001" },
    { name: "OHSAS 18001", uid: "ohsas_18001" },
  ];
  
  export const paymentTerms = [
    { name: "Net 30", uid: "net_30" },
    { name: "Net 45", uid: "net_45" },
    { name: "Net 60", uid: "net_60" },
  ];
  
  export const creditRatings = [
    { name: "A+", uid: "a_plus" },
    { name: "A", uid: "a" },
    { name: "B+", uid: "b_plus" },
    { name: "B", uid: "b" },
  ];
  
  export const suppliers = [
    {
      id: 1,
      companyName: "LogiTech Supplies",
      contactPerson: "John Doe",
      contactDetails: { phone: "123-456-7890", email: "john.doe@logitech.com" },
      address: "123 Logistics St, City, Country",
      registrationNumber: "REG12345",
      taxId: "TAX12345",
      yearsInOperation: 10,
      supplierType: "Manufacturer",
      industryCertifications: ["ISO 9001"],
      vehiclesInfo: [
        {
          vehicleId: 1,
          type: "HGV",
          makeModel: "Scania R Series",
          year: 2020,
          registrationNumber: "REG1",
          insurance: { provider: "Insurance Co", policyNumber: "POL123", expiry: "2024-01-01" },
          maintenance: "2024-01-01",
          gpsTracking: true,
          availabilityStatus: "Available",
        },
      ],
      paymentTerms: "Net 30",
      bankDetails: { accountNumber: "12345678", bankName: "Global Bank" },
      creditRating: "A+",
      pricingList: [{ item: "HGV", price: 20000 }],
      contractDetails: "Contract details here",
      compliance: "Compliant",
      legalDisputes: "None",
    },
    {
      id: 2,
      companyName: "Transport Inc",
      contactPerson: "Jane Smith",
      contactDetails: { phone: "987-654-3210", email: "jane.smith@transportinc.com" },
      address: "456 Transport Ave, City, Country",
      registrationNumber: "REG54321",
      taxId: "TAX54321",
      yearsInOperation: 15,
      supplierType: "Leasing Company",
      industryCertifications: ["ISO 14001"],
      vehiclesInfo: [
        {
          vehicleId: 2,
          type: "LCV",
          makeModel: "Volvo FH Series",
          year: 2019,
          registrationNumber: "REG2",
          insurance: { provider: "Insurance Corp", policyNumber: "POL456", expiry: "2024-02-15" },
          maintenance: "2024-02-15",
          gpsTracking: true,
          availabilityStatus: "Not Available",
        },
      ],
      paymentTerms: "Net 45",
      bankDetails: { accountNumber: "87654321", bankName: "International Bank" },
      creditRating: "A",
      pricingList: [{ item: "LCV", price: 15000 }],
      contractDetails: "Contract details here",
      compliance: "Compliant",
      legalDisputes: "None",
    },
    {
      id: 3,
      companyName: "Fleet Solutions",
      contactPerson: "Emily Davis",
      contactDetails: { phone: "555-123-4567", email: "emily.davis@fleetsolutions.com" },
      address: "789 Fleet Rd, City, Country",
      registrationNumber: "REG67890",
      taxId: "TAX67890",
      yearsInOperation: 8,
      supplierType: "Distributor",
      industryCertifications: ["ISO 9001", "ISO 14001"],
      vehiclesInfo: [
        {
          vehicleId: 3,
          type: "HGV",
          makeModel: "MAN TGX",
          year: 2021,
          registrationNumber: "REG3",
          insurance: { provider: "Secure Insurance", policyNumber: "POL789", expiry: "2024-03-20" },
          maintenance: "2024-03-20",
          gpsTracking: true,
          availabilityStatus: "Available",
        },
      ],
      paymentTerms: "Net 30",
      bankDetails: { accountNumber: "23456789", bankName: "National Bank" },
      creditRating: "A+",
      pricingList: [{ item: "HGV", price: 22000 }],
      contractDetails: "Contract details here",
      compliance: "Compliant",
      legalDisputes: "None",
    },
    {
      id: 4,
      companyName: "Heavy Haulers",
      contactPerson: "Michael Brown",
      contactDetails: { phone: "444-555-6666", email: "michael.brown@heavyhaulers.com" },
      address: "321 Haulage Ln, City, Country",
      registrationNumber: "REG11122",
      taxId: "TAX11122",
      yearsInOperation: 20,
      supplierType: "Manufacturer",
      industryCertifications: ["ISO 45001"],
      vehiclesInfo: [
        {
          vehicleId: 4,
          type: "LCV",
          makeModel: "Mercedes-Benz Actros",
          year: 2018,
          registrationNumber: "REG4",
          insurance: { provider: "Trust Insurance", policyNumber: "POL111", expiry: "2024-04-10" },
          maintenance: "2024-04-10",
          gpsTracking: false,
          availabilityStatus: "Available",
        },
      ],
      paymentTerms: "Net 60",
      bankDetails: { accountNumber: "34567890", bankName: "City Bank" },
      creditRating: "B+",
      pricingList: [{ item: "LCV", price: 18000 }],
      contractDetails: "Contract details here",
      compliance: "Compliant",
      legalDisputes: "None",
    },
    {
      id: 5,
      companyName: "Urban Transport",
      contactPerson: "Olivia Johnson",
      contactDetails: { phone: "222-333-4444", email: "olivia.johnson@urbantransport.com" },
      address: "987 Urban Blvd, City, Country",
      registrationNumber: "REG33344",
      taxId: "TAX33344",
      yearsInOperation: 12,
      supplierType: "Leasing Company",
      industryCertifications: ["ISO 9001", "ISO 45001"],
      vehiclesInfo: [
        {
          vehicleId: 5,
          type: "HGV",
          makeModel: "Renault T-Series",
          year: 2017,
          registrationNumber: "REG5",
          insurance: { provider: "Global Insurance", policyNumber: "POL222", expiry: "2024-05-15" },
          maintenance: "2024-05-15",
          gpsTracking: true,
          availabilityStatus: "Not Available",
        },
      ],
      paymentTerms: "Net 45",
      bankDetails: { accountNumber: "45678901", bankName: "Local Bank" },
      creditRating: "A",
      pricingList: [{ item: "HGV", price: 21000 }],
      contractDetails: "Contract details here",
      compliance: "Compliant",
      legalDisputes: "None",
    },
    {
      id: 6,
      companyName: "Cargo Masters",
      contactPerson: "Sophia Wilson",
      contactDetails: { phone: "666-777-8888", email: "sophia.wilson@cargomasters.com" },
      address: "654 Cargo Pl, City, Country",
      registrationNumber: "REG55566",
      taxId: "TAX55566",
      yearsInOperation: 25,
      supplierType: "Distributor",
      industryCertifications: ["ISO 9001", "OHSAS 18001"],
      vehiclesInfo: [
        {
          vehicleId: 6,
          type: "LCV",
          makeModel: "DAF XF",
          year: 2016,
          registrationNumber: "REG6",
          insurance: { provider: "Premium Insurance", policyNumber: "POL333", expiry: "2024-06-20" },
          maintenance: "2024-06-20",
          gpsTracking: false,
          availabilityStatus: "Available",
        },
      ],
      paymentTerms: "Net 60",
      bankDetails: { accountNumber: "56789012", bankName: "Major Bank" },
      creditRating: "A+",
      pricingList: [{ item: "LCV", price: 17500 }],
      contractDetails: "Contract details here",
      compliance: "Compliant",
      legalDisputes: "None",
    },
    {
      id: 7,
      companyName: "Fleet Enterprises",
      contactPerson: "Liam Martinez",
      contactDetails: { phone: "999-000-1111", email: "liam.martinez@fleetenterprises.com" },
      address: "321 Fleet St, City, Country",
      registrationNumber: "REG77788",
      taxId: "TAX77788",
      yearsInOperation: 18,
      supplierType: "Retailer",
      industryCertifications: ["ISO 14001"],
      vehiclesInfo: [
        {
          vehicleId: 7,
          type: "HGV",
          makeModel: "Iveco Stralis",
          year: 2015,
          registrationNumber: "REG7",
          insurance: { provider: "Reliable Insurance", policyNumber: "POL444", expiry: "2024-07-25" },
          maintenance: "2024-07-25",
          gpsTracking: true,
          availabilityStatus: "Available",
        },
      ],
      paymentTerms: "Net 30",
      bankDetails: { accountNumber: "67890123", bankName: "Top Bank" },
      creditRating: "B",
      pricingList: [{ item: "HGV", price: 19500 }],
      contractDetails: "Contract details here",
      compliance: "Compliant",
      legalDisputes: "None",
    },
    {
      id: 8,
      companyName: "Trans Logistics",
      contactPerson: "Mason Lee",
      contactDetails: { phone: "888-999-0000", email: "mason.lee@translogistics.com" },
      address: "123 Transport St, City, Country",
      registrationNumber: "REG99900",
      taxId: "TAX99900",
      yearsInOperation: 22,
      supplierType: "Manufacturer",
      industryCertifications: ["ISO 9001", "ISO 45001"],
      vehiclesInfo: [
        {
          vehicleId: 8,
          type: "LCV",
          makeModel: "Volvo FM",
          year: 2014,
          registrationNumber: "REG8",
          insurance: { provider: "Elite Insurance", policyNumber: "POL555", expiry: "2024-08-30" },
          maintenance: "2024-08-30",
          gpsTracking: false,
          availabilityStatus: "Not Available",
        },
      ],
      paymentTerms: "Net 45",
      bankDetails: { accountNumber: "78901234", bankName: "Prime Bank" },
      creditRating: "A+",
      pricingList: [{ item: "LCV", price: 18500 }],
      contractDetails: "Contract details here",
      compliance: "Compliant",
      legalDisputes: "None",
    },
    {
      id: 9,
      companyName: "Logistics Partners",
      contactPerson: "Isabella White",
      contactDetails: { phone: "777-888-9999", email: "isabella.white@logisticspartners.com" },
      address: "456 Logistics Ln, City, Country",
      registrationNumber: "REG11122",
      taxId: "TAX11122",
      yearsInOperation: 30,
      supplierType: "Distributor",
      industryCertifications: ["ISO 14001", "OHSAS 18001"],
      vehiclesInfo: [
        {
          vehicleId: 9,
          type: "HGV",
          makeModel: "Scania S Series",
          year: 2013,
          registrationNumber: "REG9",
          insurance: { provider: "Superior Insurance", policyNumber: "POL666", expiry: "2024-09-10" },
          maintenance: "2024-09-10",
          gpsTracking: true,
          availabilityStatus: "Available",
        },
      ],
      paymentTerms: "Net 60",
      bankDetails: { accountNumber: "89012345", bankName: "Superior Bank" },
      creditRating: "A",
      pricingList: [{ item: "HGV", price: 23000 }],
      contractDetails: "Contract details here",
      compliance: "Compliant",
      legalDisputes: "None",
    },
    {
      id: 10,
      companyName: "Cargo Transporters",
      contactPerson: "Alexander Harris",
      contactDetails: { phone: "666-777-8888", email: "alexander.harris@cargotransporters.com" },
      address: "789 Cargo Rd, City, Country",
      registrationNumber: "REG33344",
      taxId: "TAX33344",
      yearsInOperation: 5,
      supplierType: "Leasing Company",
      industryCertifications: ["ISO 9001"],
      vehiclesInfo: [
        {
          vehicleId: 10,
          type: "LCV",
          makeModel: "MAN TGS",
          year: 2012,
          registrationNumber: "REG10",
          insurance: { provider: "Trusted Insurance", policyNumber: "POL777", expiry: "2024-10-15" },
          maintenance: "2024-10-15",
          gpsTracking: false,
          availabilityStatus: "Available",
        },
      ],
      paymentTerms: "Net 30",
      bankDetails: { accountNumber: "90123456", bankName: "Trust Bank" },
      creditRating: "B+",
      pricingList: [{ item: "LCV", price: 16000 }],
      contractDetails: "Contract details here",
      compliance: "Compliant",
      legalDisputes: "None",
    },
    {
      id: 11,
      companyName: "Fleet Network",
      contactPerson: "James Clark",
      contactDetails: { phone: "444-555-6666", email: "james.clark@fleetnetwork.com" },
      address: "321 Fleet Ave, City, Country",
      registrationNumber: "REG55566",
      taxId: "TAX55566",
      yearsInOperation: 12,
      supplierType: "Retailer",
      industryCertifications: ["ISO 9001", "ISO 45001"],
      vehiclesInfo: [
        {
          vehicleId: 11,
          type: "HGV",
          makeModel: "Renault Premium",
          year: 2011,
          registrationNumber: "REG11",
          insurance: { provider: "Reliable Insurance", policyNumber: "POL888", expiry: "2024-11-20" },
          maintenance: "2024-11-20",
          gpsTracking: true,
          availabilityStatus: "Not Available",
        },
      ],
      paymentTerms: "Net 45",
      bankDetails: { accountNumber: "23456789", bankName: "Reliable Bank" },
      creditRating: "A+",
      pricingList: [{ item: "HGV", price: 22000 }],
      contractDetails: "Contract details here",
      compliance: "Compliant",
      legalDisputes: "None",
    },
    {
      id: 12,
      companyName: "Cargo Solutions",
      contactPerson: "William Walker",
      contactDetails: { phone: "333-444-5555", email: "william.walker@cargosolutions.com" },
      address: "987 Cargo Blvd, City, Country",
      registrationNumber: "REG77788",
      taxId: "TAX77788",
      yearsInOperation: 18,
      supplierType: "Manufacturer",
      industryCertifications: ["ISO 14001", "OHSAS 18001"],
      vehiclesInfo: [
        {
          vehicleId: 12,
          type: "LCV",
          makeModel: "Iveco Eurocargo",
          year: 2010,
          registrationNumber: "REG12",
          insurance: { provider: "Secure Insurance", policyNumber: "POL999", expiry: "2024-12-25" },
          maintenance: "2024-12-25",
          gpsTracking: false,
          availabilityStatus: "Available",
        },
      ],
      paymentTerms: "Net 60",
      bankDetails: { accountNumber: "34567890", bankName: "Secure Bank" },
      creditRating: "A",
      pricingList: [{ item: "LCV", price: 17000 }],
      contractDetails: "Contract details here",
      compliance: "Compliant",
      legalDisputes: "None",
    },
    {
      id: 13,
      companyName: "Urban Logistics",
      contactPerson: "Emma Scott",
      contactDetails: { phone: "222-333-4444", email: "emma.scott@urbanlogistics.com" },
      address: "654 Urban St, City, Country",
      registrationNumber: "REG99900",
      taxId: "TAX99900",
      yearsInOperation: 7,
      supplierType: "Leasing Company",
      industryCertifications: ["ISO 9001", "ISO 45001"],
      vehiclesInfo: [
        {
          vehicleId: 13,
          type: "HGV",
          makeModel: "DAF LF",
          year: 2009,
          registrationNumber: "REG13",
          insurance: { provider: "Global Insurance", policyNumber: "POL111", expiry: "2024-01-01" },
          maintenance: "2024-01-01",
          gpsTracking: true,
          availabilityStatus: "Not Available",
        },
      ],
      paymentTerms: "Net 45",
      bankDetails: { accountNumber: "45678901", bankName: "Local Bank" },
      creditRating: "A+",
      pricingList: [{ item: "HGV", price: 21000 }],
      contractDetails: "Contract details here",
      compliance: "Compliant",
      legalDisputes: "None",
    },
    {
      id: 14,
      companyName: "Heavy Logistics",
      contactPerson: "Lucas Rodriguez",
      contactDetails: { phone: "666-777-8888", email: "lucas.rodriguez@heavylogistics.com" },
      address: "123 Heavy Ln, City, Country",
      registrationNumber: "REG11122",
      taxId: "TAX11122",
      yearsInOperation: 9,
      supplierType: "Distributor",
      industryCertifications: ["ISO 14001"],
      vehiclesInfo: [
        {
          vehicleId: 14,
          type: "LCV",
          makeModel: "Volvo FE",
          year: 2008,
          registrationNumber: "REG14",
          insurance: { provider: "Premium Insurance", policyNumber: "POL222", expiry: "2024-02-15" },
          maintenance: "2024-02-15",
          gpsTracking: false,
          availabilityStatus: "Available",
        },
      ],
      paymentTerms: "Net 30",
      bankDetails: { accountNumber: "56789012", bankName: "Major Bank" },
      creditRating: "B+",
      pricingList: [{ item: "LCV", price: 17500 }],
      contractDetails: "Contract details here",
      compliance: "Compliant",
      legalDisputes: "None",
    },
    {
      id: 15,
      companyName: "Fleet Services",
      contactPerson: "Benjamin Hall",
      contactDetails: { phone: "999-000-1111", email: "benjamin.hall@fleetservices.com" },
      address: "789 Fleet Rd, City, Country",
      registrationNumber: "REG33344",
      taxId: "TAX33344",
      yearsInOperation: 16,
      supplierType: "Retailer",
      industryCertifications: ["ISO 9001"],
      vehiclesInfo: [
        {
          vehicleId: 15,
          type: "HGV",
          makeModel: "MAN TGA",
          year: 2007,
          registrationNumber: "REG15",
          insurance: { provider: "Trust Insurance", policyNumber: "POL333", expiry: "2024-03-20" },
          maintenance: "2024-03-20",
          gpsTracking: true,
          availabilityStatus: "Available",
        },
      ],
      paymentTerms: "Net 45",
      bankDetails: { accountNumber: "67890123", bankName: "Top Bank" },
      creditRating: "B",
      pricingList: [{ item: "HGV", price: 19500 }],
      contractDetails: "Contract details here",
      compliance: "Compliant",
      legalDisputes: "None",
    },
    {
      id: 16,
      companyName: "Transport Logistics",
      contactPerson: "Ava Allen",
      contactDetails: { phone: "888-999-0000", email: "ava.allen@transportlogistics.com" },
      address: "321 Transport St, City, Country",
      registrationNumber: "REG55566",
      taxId: "TAX55566",
      yearsInOperation: 4,
      supplierType: "Manufacturer",
      industryCertifications: ["ISO 9001", "ISO 45001"],
      vehiclesInfo: [
        {
          vehicleId: 16,
          type: "LCV",
          makeModel: "Iveco Daily",
          year: 2006,
          registrationNumber: "REG16",
          insurance: { provider: "Elite Insurance", policyNumber: "POL444", expiry: "2024-04-25" },
          maintenance: "2024-04-25",
          gpsTracking: false,
          availabilityStatus: "Available",
        },
      ],
      paymentTerms: "Net 30",
      bankDetails: { accountNumber: "78901234", bankName: "Prime Bank" },
      creditRating: "A+",
      pricingList: [{ item: "LCV", price: 18500 }],
      contractDetails: "Contract details here",
      compliance: "Compliant",
      legalDisputes: "None",
    },
    {
      id: 17,
      companyName: "Cargo Fleet",
      contactPerson: "Mia Robinson",
      contactDetails: { phone: "777-888-9999", email: "mia.robinson@cargofleet.com" },
      address: "654 Cargo St, City, Country",
      registrationNumber: "REG99900",
      taxId: "TAX99900",
      yearsInOperation: 3,
      supplierType: "Distributor",
      industryCertifications: ["ISO 9001", "OHSAS 18001"],
      vehiclesInfo: [
        {
          vehicleId: 17,
          type: "HGV",
          makeModel: "DAF CF",
          year: 2005,
          registrationNumber: "REG17",
          insurance: { provider: "Superior Insurance", policyNumber: "POL555", expiry: "2024-05-30" },
          maintenance: "2024-05-30",
          gpsTracking: true,
          availabilityStatus: "Not Available",
        },
      ],
      paymentTerms: "Net 45",
      bankDetails: { accountNumber: "89012345", bankName: "Superior Bank" },
      creditRating: "A",
      pricingList: [{ item: "HGV", price: 23000 }],
      contractDetails: "Contract details here",
      compliance: "Compliant",
      legalDisputes: "None",
    },
    {
      id: 18,
      companyName: "Transport Enterprises",
      contactPerson: "Ethan Young",
      contactDetails: { phone: "666-777-8888", email: "ethan.young@transportenterprises.com" },
      address: "987 Transport Ave, City, Country",
      registrationNumber: "REG11122",
      taxId: "TAX11122",
      yearsInOperation: 6,
      supplierType: "Leasing Company",
      industryCertifications: ["ISO 9001"],
      vehiclesInfo: [
        {
          vehicleId: 18,
          type: "LCV",
          makeModel: "Mercedes-Benz Vario",
          year: 2004,
          registrationNumber: "REG18",
          insurance: { provider: "Trusted Insurance", policyNumber: "POL666", expiry: "2024-06-15" },
          maintenance: "2024-06-15",
          gpsTracking: false,
          availabilityStatus: "Available",
        },
      ],
      paymentTerms: "Net 60",
      bankDetails: { accountNumber: "90123456", bankName: "Trust Bank" },
      creditRating: "B+",
      pricingList: [{ item: "LCV", price: 16000 }],
      contractDetails: "Contract details here",
      compliance: "Compliant",
      legalDisputes: "None",
    },
    {
      id: 19,
      companyName: "Heavy Duty Logistics",
      contactPerson: "Michael Martinez",
      contactDetails: { phone: "444-555-6666", email: "michael.martinez@heavydutylogistics.com" },
      address: "123 Heavy Rd, City, Country",
      registrationNumber: "REG33344",
      taxId: "TAX33344",
      yearsInOperation: 11,
      supplierType: "Manufacturer",
      industryCertifications: ["ISO 14001", "ISO 45001"],
      vehiclesInfo: [
        {
          vehicleId: 19,
          type: "HGV",
          makeModel: "Volvo FL",
          year: 2003,
          registrationNumber: "REG19",
          insurance: { provider: "Reliable Insurance", policyNumber: "POL777", expiry: "2024-07-10" },
          maintenance: "2024-07-10",
          gpsTracking: true,
          availabilityStatus: "Not Available",
        },
      ],
      paymentTerms: "Net 45",
      bankDetails: { accountNumber: "23456789", bankName: "Reliable Bank" },
      creditRating: "A+",
      pricingList: [{ item: "HGV", price: 22000 }],
      contractDetails: "Contract details here",
      compliance: "Compliant",
      legalDisputes: "None",
    },
    {
      id: 20,
      companyName: "Fleet Freight",
      contactPerson: "Sophia Hernandez",
      contactDetails: { phone: "333-444-5555", email: "sophia.hernandez@fleetfreight.com" },
      address: "987 Fleet Ln, City, Country",
      registrationNumber: "REG55566",
      taxId: "TAX55566",
      yearsInOperation: 14,
      supplierType: "Leasing Company",
      industryCertifications: ["ISO 9001", "OHSAS 18001"],
      vehiclesInfo: [
        {
          vehicleId: 20,
          type: "LCV",
          makeModel: "Renault D-Series",
          year: 2002,
          registrationNumber: "REG20",
          insurance: { provider: "Secure Insurance", policyNumber: "POL888", expiry: "2024-08-25" },
          maintenance: "2024-08-25",
          gpsTracking: false,
          availabilityStatus: "Available",
        },
      ],
      paymentTerms: "Net 30",
      bankDetails: { accountNumber: "34567890", bankName: "Secure Bank" },
      creditRating: "A",
      pricingList: [{ item: "LCV", price: 17000 }],
      contractDetails: "Contract details here",
      compliance: "Compliant",
      legalDisputes: "None",
    },
  ];
  